#versión de docker-compose 3.8 es la más reciente
version: "3.8"

volumes:
    #Aquí se definen los volumenes/almacenamiento de los contenedores
    #Gitlab
    GITLAB_CONFIG:
        external: true
    GITLAB_LOGS:
        external: true
    GITLAB_DATA:
        external: true
    #Nexus
    NEXUS_DATA:
        external: true
    #Runner
    runner_data:
        external: true

# networks:
    #Aquí se definen las redes utilizadas por los contenedores


services:

    #--- HAProxy ---

    haproxy:
        depends_on: 
            - gitlab
            # - nexus
        restart: unless-stopped
        image: haproxy:2.2-dev7-alpine
        container_name: haproxy
        volumes:
            - ./haproxy:/usr/local/etc/haproxy/
        ports:
            - "80:80"
            - "443:443"

    #--- Gitlab ---
    
    gitlab:
        container_name: gitlab
        restart: unless-stopped
        image: gitlab/gitlab-ce:13.0.6-ce.0
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://host.docker.internal/gitlab'
                gitlab_rails['gitlab_shell_ssh_port'] = 2222
        ports:
            # - '8080:80'
            #ssh port desde el que se accede desde el exterior 'gitlab_shell_ssh_port'
            - "2222:22"
            - "8080:80"
        volumes:
            - GITLAB_CONFIG:/etc/gitlab
            - GITLAB_LOGS:/var/log/gitlab
            - GITLAB_DATA:/var/opt/gitlab
            - ./haproxy/haproxy.pem:/etc/gitlab/ssl/haproxy.pem

    #--- Nexus ---
        
    # nexus:
    #     container_name: nexus
    #     image: sonatype/nexus3:3.24.0
    #     restart: unless-stopped
    #     environment:
    #         - NEXUS_CONTEXT=nexus
    #     volumes:
    #         - NEXUS_DATA:/nexus-data
    #     ports:
    #         - '8082:8082'
    #         - '8083:8083'

    # --- Runner ---

    runner:
        depends_on: 
            - gitlab
        container_name: runner
        image: gitlab/gitlab-runner
        restart: unless-stopped
        environment:
            - RUNNER_TAG_LIST 
            - GITLAB_URL
            - TOKEN
            - RUNNER_NAME
            - RUNNER_TAG_LIST="test,proyecto"
            # To not verify = 1
            - RUNNER_ENV=GIT_SSL_NO_VERIFY=1
            - DOCKER_TLS_VERIFY=false
            - CI_SERVER_TLS_CA_FILE=/etc/ssl/haproxy.pem   
        volumes:
            - runner_data:/etc/gitlab-runner
            - /var/run/docker.sock:/var/run/docker.sock
            - ./haproxy/haproxy.pem:/etc/ssl/haproxy.pem
            - ./runner/config.toml:/etc/gitlab-runner/config.toml
            - ./runner/register.sh:/register.sh




    
