global:
    scrape_interval: 5s
    evaluation_interval: 15s

#En esta sección se definen los endpoints donde recoger la información
scrape_configs:

    # PROMETHEUS #

    - job_name: 'prometheus'
      #Tiempo de barrido -> override el valor por defecto 15s
      static_configs:
        #ruta donde corre el servicio
        - targets: ['prometheus:9090']

    # CADVISOR #

    - job_name: 'cadvisor'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['cadvisor:8080']
          labels:
            group: 'cAdvisor'

    # NODE-EXPORTER #

    - job_name: 'node_exporter'
      static_configs:
        - targets: ['node_exporter:9100']

        