concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "test"
  url = "https://host.docker.internal/gitlab"
  token = "posFkY67bBxd_CoRNc8Y"
  tls-ca-file = "/etc/ssl/haproxy.pem"
  executor = "docker"
  environment = ["GIT_SSL_NO_VERIFY=1"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    cache_dir = "/cache"
    shm_size = 0

[[runners]]
  name = "pruebas"
  url = "https://host.docker.internal/gitlab/"
  token = "N5GwPbFJshoexaqqNfmk"
  tls-ca-file = "/etc/ssl/haproxy.pem"
  executor = "docker"
  environment = ["GIT_SSL_NO_VERIFY=1"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
